# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-01 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingEstimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(max_length=150)),
                ('originZipCode', models.IntegerField(default=0)),
                ('value_of_content', models.FloatField(default=0.0)),
                ('mail_type', models.CharField(choices=[('LT', 'LETTER'), ('PKG', 'PACKAGE')], max_length=15)),
                ('destination_country', models.CharField(max_length=75)),
                ('width', models.FloatField(default=0.0)),
                ('length', models.FloatField(default=0.0)),
                ('height', models.FloatField(default=0.0)),
                ('weight', models.FloatField(default=0.0)),
                ('item_container', models.CharField(choices=[('RECT', 'RECTANGULAR'), ('NONRECT', 'NONRECTANGULAR')], default='RECTANGULAR', max_length=15)),
                ('size', models.CharField(choices=[('REG', 'REGULAR'), ('LAR', 'LARGE')], default='LARGE', max_length=15)),
                ('shipping_estimate', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='TrackingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackingID', models.CharField(max_length=30)),
                ('trackingInfo', models.CharField(max_length=225)),
            ],
        ),
    ]
