# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-01 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingestimate',
            name='mail_type',
            field=models.CharField(choices=[('LT', 'LETTER'), ('PKG', 'PACKAGE')], default='PACKAGE', max_length=15),
        ),
        migrations.AlterField(
            model_name='shippingestimate',
            name='originZipCode',
            field=models.IntegerField(default=0, verbose_name="sender's zip code"),
        ),
    ]
