# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-03 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usps', '0002_auto_20160301_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingestimate',
            name='girth',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='shippingestimate',
            name='item_container',
            field=models.CharField(choices=[('RECTANGULAR', 'RECTANGULAR'), ('NONRECTANGULAR', 'NONRECTANGULAR')], default='RECTANGULAR', max_length=15),
        ),
        migrations.AlterField(
            model_name='shippingestimate',
            name='mail_type',
            field=models.CharField(choices=[('LETTER', 'LETTER'), ('PACKAGE', 'PACKAGE')], default='PACKAGE', max_length=15),
        ),
        migrations.AlterField(
            model_name='shippingestimate',
            name='size',
            field=models.CharField(choices=[('REGULAR', 'REGULAR'), ('LARGE', 'LARGE')], default='LARGE', max_length=15),
        ),
    ]
