# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-07 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usps', '0003_auto_20160303_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingestimate',
            name='girth',
        ),
    ]
