# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-08 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usps', '0004_remove_shippingestimate_girth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingestimate',
            name='item_container',
            field=models.CharField(choices=[('RECTANGULAR', 'RECTANGULAR')], default='RECTANGULAR', max_length=15),
        ),
    ]
